// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/": InferRoute<import("./src/app/route-type").RouteType>;
    "/skills/new": InferRoute<import("./src/app/skills/new/route-type").RouteType>;
    "/skills/[id]": InferRoute<import("./src/app/skills/[id]/route-type").RouteType>;
  }

  interface StaticRouter {
  
  }
}
